### PR TITLE
Batched version

### PR DESCRIPTION
**Pull request by mnicely**
This combined batched + cufftw + OpenMP

~Still investigating why batched + cufftw + OpenMP > 1 is less performant~

### CODE REVIEW

**Comment by mnicely** [comment]
### Results Batched (OFF) + cufftw (OFF) + openmp (1)
```bash
belt@orion:~/workStuff/hackathon/2D_Program$ ./Direct_Solver 6 10000 1
        6th Order
        Grid 10000 x 10000
        OpenMP Threads: 1

        Set up time = 36.949886 sec 
        Set up wall-time = 36.951213 sec 
        Set up wall-time (sys/time) = 36.951213 sec 

        Solver time = 23.651699 sec 
        Solver wall-time = 23.652254 sec 
        Solver wall-time (sys/time) = 23.652255 sec 

        ||res||_inf =  9.4146054e-15 

        ||error||_inf =  8.3414895e-10
```

### Results Batched (OFF) + cufftw (OFF) + openmp (8)
```bash
belt@orion:~/workStuff/hackathon/2D_Program$ ./Direct_Solver 6 10000 8

        6th Order
        Grid 10000 x 10000
        OpenMP Threads: 8

        Set up time = 124.003677 sec 
        Set up wall-time = 21.547973 sec 
        Set up wall-time (sys/time) = 21.547972 sec 

        Solver time = 28.825235 sec 
        Solver wall-time = 3.842534 sec 
        Solver wall-time (sys/time) = 3.842533 sec 

        ||res||_inf =  9.4146054e-15 

        ||error||_inf =  8.3414895e-10
```

**Comment by mnicely** [comment]
### Results Batched (OFF) + cufftw (ON) + openmp (1)
```bash
belt@orion:~/workStuff/hackathon/2D_Program$ ./Direct_Solver 6 10000 1
        6th Order
        Grid 10000 x 10000
        OpenMP Threads: 1

        Set up time = 36.321918 sec 
        Set up wall-time = 36.324271 sec 
        Set up wall-time (sys/time) = 36.324271 sec 

        Solver time = 11.938057 sec 
        Solver wall-time = 11.938415 sec 
        Solver wall-time (sys/time) = 11.938416 sec 

        ||res||_inf =  8.2175233e-15 

        ||error||_inf =  8.3414148e-10
```

### Results Batched (OFF) + cufftw (ON) + openmp (8)
```bash
belt@orion:~/workStuff/hackathon/2D_Program$ ./Direct_Solver 6 10000 8

        6th Order
        Grid 10000 x 10000
        OpenMP Threads: 8

        Set up time = 122.448952 sec 
        Set up wall-time = 21.447075 sec 
        Set up wall-time (sys/time) = 21.447075 sec 


        Solver time = 60.116310 sec 
        Solver wall-time = 7.785645 sec 
        Solver wall-time (sys/time) = 7.785645 sec 

        ||res||_inf =  8.2175233e-15 

        ||error||_inf =  8.3414148e-10
```

**Comment by mnicely** [comment]
### Results Batched (ON) + cufftw (OFF) + openmp (1)
```bash
belt@orion:~/workStuff/hackathon/2D_Program$ ./Direct_Solver 6 10000 1

        6th Order
        Grid 10000 x 10000
        OpenMP Threads: 1

        Set up time = 36.195084 sec 
        Set up wall-time = 36.250123 sec 
        Set up wall-time (sys/time) = 36.250123 sec 

        Solver time = 103.175423 sec 
        Solver wall-time = 103.291394 sec 
        Solver wall-time (sys/time) = 103.291394 sec 

        ||res||_inf =  8.5940599e+01 

        ||error||_inf =  3.6329375e+01
```

### Results Batched (ON) + cufftw (OFF) + openmp (8)
```bash
belt@orion:~/workStuff/hackathon/2D_Program$ ./Direct_Solver 6 10000 8

6th Order
        Grid 10000 x 10000
        OpenMP Threads: 8

        Set up time = 123.689087 sec 
        Set up wall-time = 21.350037 sec 
        Set up wall-time (sys/time) = 21.350037 sec 


        Solver time = 111.008553 sec 
        Solver wall-time = 100.687663 sec 
        Solver wall-time (sys/time) = 100.687663 sec 

        ||res||_inf =  9.4146054e-15 

        ||error||_inf =  8.3414895e-10
```

**Comment by mnicely** [comment]
### Results Batched (ON) + cufftw (ON) + openmp (1)
```bash
belt@orion:~/workStuff/hackathon/2D_Program$ ./Direct_Solver 6 10000 1
        6th Order
        Grid 10000 x 10000
        OpenMP Threads: 1

        Set up time = 36.159466 sec 
        Set up wall-time = 36.161194 sec 
        Set up wall-time (sys/time) = 36.161194 sec 

        Solver time = 9.418850 sec 
        Solver wall-time = 9.433885 sec 
        Solver wall-time (sys/time) = 9.433886 sec 

        ||res||_inf =  8.2175233e-15 

        ||error||_inf =  8.3414148e-10
```

### Results Batched (ON) + cufftw (ON) + openmp (8)
```bash
belt@orion:~/workStuff/hackathon/2D_Program$ ./Direct_Solver 6 10000 8
        6th Order
        Grid 10000 x 10000
        OpenMP Threads: 8

        Set up time = 124.005112 sec 
        Set up wall-time = 21.510924 sec 
        Set up wall-time (sys/time) = 21.510924 sec 


        Solver time = 16.541430 sec 
        Solver wall-time = 6.327452 sec 
        Solver wall-time (sys/time) = 6.327453 sec 

        ||res||_inf =  8.2175233e-15 

        ||error||_inf =  8.3414148e-10
```

**Review by gonzrona — APPROVED** [review]

**Pull request merged**
